version: '3.9'
services:
  api_climbing:
    build: ./api-climbing
    container_name: api
    ports:
      - 8080:8080
    volumes:
      - ./api-climbing:/app
      - /node_modules
      - ./.env:/app/.env
    depends_on:
      - db_climbing
    environment:
      - NODE_ENV=production
    networks:
      - climbing_network
  frontend_climbing:
    build: ./frontend-climb
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend-climb:/app
      - /node_modules
    depends_on:
      - api_climbing
    networks:
      - climbing_network
    environment:
      - NODE_ENV=development
  db_climbing:
    image: mongo:latest
    container_name: climbing_db
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - climbing_network

volumes:
  mongodb_data_container:

networks:
  climbing_network:
    driver: bridge