version: '3.9'
services:
  api:
    build: ./api-climbing
    container_name: api
    ports:
      - 8080:8080
    volumes:
      - ./api-climbing:/app
      - /app/node_modules
  frontend:
    build: ./frontend-climb
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend-climb:/app
      - /app/node_modules
    depends_on:
      - api