version: '3.9'
services:
  api:
    build: ./api-climbing
    container_name: api-climbing
    ports:
      - 3001:3001
    volumes:
      - ./api-climbing:/app
      - /app/node_modules
  frontend:
    build: ./frontend-climb
    container_name: frontend-climb
    ports:
      - 3000:3000
    volumes:
      - ./frontend-climb:/app
    depends_on:
      - api