GET http://localhost:8080/api/crags/test


###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name":"Mile",
  "email": "mike@miske.cm",
  "password":"billybob20"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "mike@mike.com",
  "password": "raptor123"
}

###
POST http://localhost:8080/api/crags/addcrag
Content-Type: application/json

{
  "cragName": "cragTest4",
  "information": "this is some information",
  "cragLocation": {
    "lat": "54.475672",
    "lng": "-5.718015"
  }
}

###
POST http://localhost:8080/api/crags/addsector
Content-Type: application/json

{ 
  "currentCrag":"Belfast Crag",
  "sectorName": "Victoria Square",
  "sectorImageUrl": "TestUrl2",
  "sectorLocation": {
    "lat": 54.598247,
    "lng": -5.925295
  }
}

###
PUT http://localhost:8080/api/users/update
Content-Type: application/json

{
  
}

###
POST http://localhost:8080/api/crags/addroute
Content-Type: application/json

{
  "routeName": "Test Route",
  "routeGrade": "4",
  "routeInformation": "Test Info",
  "currentCrag": "633b3eae1b1390b8ca330a0c",
  "currentSector": "633b3ebb1b1390b8ca330a12"
}

###
PUT http://localhost:8080/api/crags/archiveSector
Content-Type: application/json

{
  "cragId": "636f54831b294bf3e9666785",
  "sectorId": "636f54951b294bf3e966678a"
}

###
PUT http://localhost:8080/api/crags/archiveCrag
Content-Type: application/json

{
  "cragId": "636fd6aba2126e56b3523cd1"
}